version: '3.4'

services:
  gungnir:
    image: xmidt/gungnir:${GUNGNIR_VERSION}
    container_name: gungnir
    restart: on-failure
    ports:
      - 7000:7000
      - 7001:7001
      - 7002:7002
      - 7003:7003
    volumes:
      - ./docFiles/gungnir.yaml:/etc/gungnir/gungnir.yaml
      - ./docFiles/private.pem:/etc/gungnir/private.pem
    networks:
      - back-tier
    depends_on:
      - yb-tserver

  svalinn:
    image: xmidt/svalinn:${SVALINN_VERSION}
    container_name: svalinn
    restart: on-failure
    ports:
      - 7100:7100
      - 7101:7101
      - 7102:7102
      - 7103:7103
    volumes:
      - ./docFiles/svalinn.yaml:/etc/svalinn/svalinn.yaml
      - ./docFiles/public.pem:/etc/svalinn/public.pem
    networks:
      - back-tier
    depends_on:
      - yb-tserver

  yb-manager:
      image: yugabytedb/yugabyte:latest
      container_name: yb-manager-n1
      command: [ "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/disk0,/mnt/disk1",
                "--master_addresses=yb-manager-n1:7100",
                "--replication_factor=1"]
      networks:
        - back-tier
      ports:
      - "7111:7000"
      environment:
        SERVICE_7000_NAME: yb-manager

  yb-tserver:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-n1
      volumes:
        - ./docFiles/create_db.cql:/create_db.cql
      command: [ "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/disk0,/mnt/disk1",
                "--tserver_master_addrs=yb-manager-n1:7100"]
      networks:
        - back-tier
      ports:
      - "9042:9042"
      - "6379:6379"
      - "5433:5433"
      - "9000:9000"
      environment:
        SERVICE_5433_NAME: ysql
        SERVICE_9042_NAME: ycql
        SERVICE_6379_NAME: yedis
        SERVICE_9000_NAME: yb-tserver
      depends_on:
      - yb-manager

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - back-tier
    ports:
      - 9090:9090
    volumes:
      - ./docFiles/prometheus.yml:/prometheus-data/prometheus.yml
    command:  --config.file=/prometheus-data/prometheus.yml

networks:
  back-tier:
