version: '3.4'

services:
  gungnir:
    image: gungnir:${GUNGNIR_VERSION}
    container_name: gungnir
    restart: on-failure
    ports:
      - 7000:7000
      - 7001:7001
      - 7002:7002
      - 7003:7003
    volumes:
      - ./docFiles/gungnir.yaml:/etc/gungnir/gungnir.yaml
      - ./docFiles/private.pem:/etc/gungnir/private.pem
    networks:
      - back-tier
    depends_on:
      - db

  svalinn:
    image: svalinn:${SVALINN_VERSION}
    container_name: svalinn
    restart: on-failure
    ports:
      - 7100:7100
      - 7101:7101
      - 7102:7102
      - 7103:7103
    volumes:
      - ./docFiles/svalinn.yaml:/etc/svalinn/svalinn.yaml
      - ./docFiles/public.pem:/etc/svalinn/public.pem
    networks:
      - back-tier
    depends_on:
      - db

  fenrir:
    image: fenrir:${FENRIR_VERSION}
    container_name: fenrir
    restart: on-failure
    ports:
      - 7203:7203
    volumes:
      - ./docFiles/fenrir.yaml:/etc/fenrir/fenrir.yaml
    networks:
      - back-tier
    depends_on:
      - db

  db:
    image: cockroachdb/cockroach:v2.1.4
    container_name: db
    command: start --insecure
    ports:
      - 26257:26257
      - 8080:8080
    networks:
      - back-tier
    volumes:
      - ./cockroach-data/roach1:/cockroach/cockroach-data
      - ./certs:/cockroach/certs


  db-init:
    image: cockroachdb/cockroach:v2.1.4
    container_name: db-init
    networks:
      - back-tier
    volumes:
      - ./setup_db.sh:/setup_db.sh
    entrypoint: "/bin/bash"
    command: /setup_db.sh
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - back-tier
    ports:
      - 9090:9090
    volumes:
      - ./docFiles/prometheus.yml:/prometheus-data/prometheus.yml
    command:  --config.file=/prometheus-data/prometheus.yml

networks:
  back-tier:
