version: '3.4'

services:
  gungnir:
    image: gungnir:${GUNGNIR_VERSION}
    restart: on-failure
    ports:
      - 7000:7000
      - 7001:7001
      - 7002:7002
      - 7003:7003
    volumes:
      - ./docFiles/gungnir.yaml:/etc/gungnir/gungnir.yaml
    networks:
      - back-tier
    depends_on:
      - db

  svalinn:
    image: svalinn:${SVALINN_VERSION}
    restart: on-failure
    ports:
      - 7100:7100
      - 7101:7101
      - 7102:7102
      - 7103:7103
    volumes:
      - ./docFiles/svalinn.yaml:/etc/svalinn/svalinn.yaml
    networks:
      - back-tier
    depends_on:
      - db

  db:
    image: cockroachdb/cockroach:v2.1.4
    command: start --insecure
    ports:
      - 26257:26257
      - 8080:8080
    networks:
      - back-tier
    volumes:
      - ./cockroach-data/roach1:/cockroach/cockroach-data
      - ./certs:/cockroach/certs

networks:
  back-tier:
